from models.book import *

book1 = Book("The Wind-Up Bird Chronicle", "Haruki Murakami", "Magical Realism", "In a Tokyo suburb a young man named Toru Okada searches for his wife's missing cat. Soon he finds himself looking for his wife as well in a netherworld that lies beneath the placid surface of Tokyo. As these searches intersect, Okada encounters a bizarre group of allies and antagonists: a psychic prostitute; a malevolent yet mediagenic politician; a cheerfully morbid sixteen-year-old-girl; and an aging war veteran who has been permanently changed by the hideous things he witnessed during Japan's forgotten campaign in Manchuria.", True)

book2 = Book("The Stranger", "Albert Camus", "Philosophical Fiction", "The Stranger is a 1942 novella by French author Albert Camus. Its theme and outlook are often cited as examples of Camus' philosophy, absurdism, coupled with existentialism, though Camus personally rejected the latter label. Through the story of an ordinary man unwittingly drawn into a senseless murder on an Algerian beach, Camus explored what he termed 'the nakedness of man faced with the absurd.' The book is a classic early modern work of anomie, alienation, and a general indifference to life.", False)

book3 = Book("The Crab that Played with the Sea", "Rudyard Kipling", "Children's Fantasy", "One of Rudyard Kipling's 'Just So Stories', published in 1902, this richly inventive children's fable explains the origin of the ebb and flow of tides, and how the rebellious Crab got its claws. The colourful illustrations take us to a place of myth: the Time of the Very Beginnings, when the Eldest Magician calls on the world's beasts to come out and play themselves in the world.", True)

book4 = Book("The Green Roasting Tin: Vegan and Vegetarian One-Dish Dinners", "Rukmini Iyer", "Cookery", "With all 75 recipes in this book, you simply pop your ingredients in a tin and let the oven do the work. From flexitarians to families, this book is for anyone who wants to eat easy veg-based meals that fit around their busy lives.", False)

books = [book1, book2, book3, book4]